---
# References:
#   - https://wiki.winehq.org/Ubuntu
- name: WineHQ > Enable i386 architecture
  command: dpkg --add-architecture i386
  changed_when: false

- name: WineHQ > Add apt repository
  import_role:
    name: add_apt_repository
  vars:
    repo_name: winehq
    repo_source: "deb https://dl.winehq.org/wine-builds/ubuntu {{ ansible_lsb.codename }} main"
    repo_arch: "{{ dpkg_arch }},i386"
    key_url: https://dl.winehq.org/wine-builds/winehq.key
    armored_key: true

- name: WineHQ > Install
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: true
  loop:
    - winehq-stable
