---
- hosts: localhost  # this will target localhost
  connection: local  # ansible usually uses ssh, but with this it will use local connection
  become: true  # enables sudo

  tasks:
    - name: hello world
      debug:
        msg: "hello world"

    - name: Install packages
      package:
        name:
          - git

    - name: Create ~/.local/bin/
      become_user: paulo
      file:
        path: ~/.local/bin/
        state: directory

    - name: Copy provision to ~/.local/bin/
      become_user: paulo
      copy:
        src: provision
        dest: ~/.local/bin/provision
        mode: 0775

    - name: Clone dotfiles to ~/.dotfiles/
      become_user: paulo
      git:
        repo: https://github.com/pauloromeira/dotfiles.git
        dest: ~/.dotfiles
