---
- hosts: all

  tasks:
    - name: hello world
      debug:
        msg: "hello world"

    - name: Create ~/.local/bin/
      become_user: paulo
      file:
        path: ~/.local/bin/
        state: directory

    - name: Copy provision to ~/.local/bin/
      become_user: paulo
      copy:
        src: provision
        dest: ~/.local/bin/provision
        mode: 0775

    - name: Swap ctrl/caps and set right alt as compose key
      become_user: paulo
      dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['ctrl:swapcaps', 'compose:ralt']"

    - name: Install packages
      become: true
      package:
        update_cache: yes
        name:
          - git
          - silversearcher-ag

    - name: Clone dotfiles to ~/.dotfiles/
      become_user: paulo
      git:
        repo: git@github.com:pauloromeira/dotfiles.git
        dest: ~/.dotfiles
        accept_newhostkey: true
