---
- hosts: all
  become: false
  tags: full,always
  pre_tasks:
    - import_tasks: tasks/requirements.yml
      tags: requirements


- hosts: all
  become: true
  tags: full
  pre_tasks:
    - import_tasks: tasks/config/provision.yml
      tags: config,provision

  tasks:
    - import_tasks: tasks/package/hardware.yml
      tags: package,hw,hardware

    - import_tasks: tasks/package/system.yml
      tags: package,cli,cmdline,system

    - import_tasks: tasks/package/pipx.yml
      tags: package,cli,cmdline,pipx

    - import_tasks: tasks/config/dotfiles.yml
      tags: config,dotfiles

    - import_tasks: tasks/config/locale.yml
      tags: config,locale

    - import_tasks: tasks/config/privacy.yml
      tags: config,privacy

    - import_tasks: tasks/config/power.yml
      tags: config,power

    - import_tasks: tasks/config/peripherals.yml
      tags: config,peripherals

    - import_tasks: tasks/config/sound.yml
      tags: config,sound

    - import_tasks: tasks/config/media.yml
      tags: config,media

    - import_tasks: tasks/config/tiling.yml
      tags: config,tiling

    - import_tasks: tasks/config/workspaces.yml
      tags: config,workspaces

    - import_tasks: tasks/config/terminal.yml
      tags: config,terminal

    - import_tasks: tasks/package/tmux.yml
      tags: package,cli,cmdline,tmux

    - import_tasks: tasks/package/vim.yml
      tags: package,cli,cmdline,vim

    - import_tasks: tasks/package/asdf.yml
      tags: package,cli,cmdline,asdf

    - import_tasks: tasks/package/pyenv.yml
      tags: package,cli,cmdline,pyenv

    - import_tasks: tasks/package/tlp.yml
      tags: package,cli,cmdline,tlp
      when: ansible_distribution != "Pop!_OS"  # not recommended: https://support.system76.com/articles/battery/

    - import_tasks: tasks/package/docker.yml
      tags: package,cli,cmdline,docker

    - import_tasks: tasks/package/dive.yml
      tags: package,cli,cmdline,dive

    - import_tasks: tasks/package/1password-cli.yml
      tags: package,cli,cmdline,1password,1password-cli

    - import_tasks: tasks/package/aws-ssm-plugin.yml
      tags: package,cli,cmdline,aws-ssm-plugin

    # Installed via asdf
    # - import_tasks: tasks/package/kubectl.yml
    #   tags: package,cli,cmdline,kubectl

    - name: GUI tasks
      when: user_desktop
      tags: gui,desktop,graphical
      block:
        - import_tasks: tasks/config/dock.yml
          tags: config,dock,appearance

        - import_tasks: tasks/config/wallpaper.yml
          tags: never,config,wallpaper,appearance

        - import_tasks: tasks/config/icon.yml
          tags: never,config,icon,appearance

        - import_tasks: tasks/package/gnome-extensions.yml
          tags: never,package,gnome-extensions,gnome-shell-extensions

        - import_tasks: tasks/package/graphical.yml
          tags: never,package

        - import_tasks: tasks/package/virtualbox.yml
          tags: never,package,virtualbox

        # TODO: cli but depends on virtualbox
        - import_tasks: tasks/package/vagrant.yml
          tags: never,package,vagrant

        - import_tasks: tasks/package/vscode.yml
          tags: never,package,vscode

        - import_tasks: tasks/package/qbittorrent.yml
          tags: never,package,qbittorrent

        - import_tasks: tasks/package/syncthing.yml
          tags: never,package,syncthing

        - import_tasks: tasks/package/wireshark.yml
          tags: never,package,wireshark

        - import_tasks: tasks/package/mono.yml
          tags: never,package,mono

        - import_tasks: tasks/package/winehq.yml
          tags: never,package,winehq,wine

        # - import_tasks: tasks/package/insync.yml
        #   tags: never,package,insync


- hosts: all
  become: false
  tags: never,debug
  tasks:
    - import_tasks: tasks/debug.yml
