---
- hosts: all

  tasks:
    - name: hello world
      debug:
        msg: "hello world"

    - name: Create ~/.local/bin/
      become_user: paulo
      file:
        path: ~/.local/bin/
        state: directory

    - name: Copy provision to ~/.local/bin/
      become_user: paulo
      copy:
        src: provision
        dest: ~/.local/bin/provision
        mode: 0775

    - name: Swap ctrl/caps and set right alt as compose key
      become_user: paulo
      dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['ctrl:swapcaps', 'compose:ralt']"

    - name: Install packages
      become: true
      package:
        update_cache: yes
        name:
          - git
          - silversearcher-ag

    - name: Clone dotfiles to ~/.dotfiles/
      tags: dotfiles
      become_user: paulo
      git:
        repo: https://github.com/pauloromeira/dotfiles.git
        remote: provision
        dest: ~/.dotfiles

    - name: Set dotfiles remote origin url
      tags: dotfiles
      git_config:
        repo: ~/.dotfiles
        scope: local
        name: remote.origin.url
        value: git@github.com:pauloromeira/dotfiles.git

    - name: Set dotfiles remote origin fetch
      tags: dotfiles
      git_config:
        repo: ~/.dotfiles
        scope: local
        name: remote.origin.fetch
        value: "+refs/heads/*:refs/remotes/origin/*"

    - name: Set master remote to origin
      tags: dotfiles
      git_config:
        repo: ~/.dotfiles
        scope: local
        name: branch.master.remote
        value: origin
