---
- hosts: all
  become: false
  tags: full
  pre_tasks:
    - import_tasks: tasks/facts.yml
      tags: facts,always

- hosts: all
  become: true
  tags: full
  pre_tasks:
    - import_tasks: tasks/config/provision.yml
      tags: config,provision

    - import_tasks: tasks/package/update_cache.yml
      tags: package,update,upgrade

  tasks:
    - import_tasks: tasks/package/cmdline.yml
      tags: package,cli,cmdline

    - import_tasks: tasks/package/hardware.yml
      tags: package,hw,hardware

    - import_tasks: tasks/config/keyboard.yml
      tags: config,keyboard

    - import_tasks: tasks/config/dotfiles.yml
      tags: config,dotfiles

    - import_tasks: tasks/package/tmux.yml
      tags: package,cli,cmdline,tmux

    - import_tasks: tasks/package/vim.yml
      tags: package,cli,cmdline,vim

    - import_tasks: tasks/package/docker.yml
      tags: package,cli,cmdline,docker

    - import_tasks: tasks/package/tlp.yml
      tags: package,cli,cmdline,tlp

    - import_tasks: tasks/config/dock.yml
      tags: config,dock,gui,desktop,appearance
      when: user_desktop

    - import_tasks: tasks/config/wallpaper.yml
      tags: config,wallpaper,gui,desktop,appearance
      when: user_desktop

    - import_tasks: tasks/package/virtualbox.yml
      tags: never,package,gui,desktop,graphical,virtualbox
      when: user_desktop

    - import_tasks: tasks/package/graphical.yml
      tags: never,package,gui,desktop,graphical
      when: user_desktop

- hosts: all
  become: false
  tags: never,debug
  tasks:
    - import_tasks: tasks/debug.yml
