---
- hosts: all
  become: true

  pre_tasks:
    - import_tasks: tasks/config/provision.yml
      tags: config,provision

    - import_tasks: tasks/package/update_cache.yml
      tags: package,update,upgrade,install

  tasks:
    - import_tasks: tasks/package/cmdline.yml
      tags: package,install,cli,cmdline

    - import_tasks: tasks/package/graphical.yml
      tags: package,install,gui,graphical

    - import_tasks: tasks/package/hardware.yml
      tags: package,install,hw,hardware

    - import_tasks: tasks/config/keyboard.yml
      tags: config,keyboard

    - import_tasks: tasks/config/dotfiles.yml
      tags: config,dotfiles

    - import_tasks: tasks/config/wallpaper.yml
      tags: config,wallpaper,appearance
