---
- hosts: all
  become: false
  tags: full,always
  pre_tasks:
    - import_tasks: tasks/facts.yml
      tags: facts


- hosts: all
  become: true
  tags: full
  pre_tasks:
    - import_tasks: tasks/config/provision.yml
      tags: config,provision

    - import_tasks: tasks/package/update_cache.yml
      tags: package,update,upgrade

  tasks:
    - import_tasks: tasks/package/cmdline.yml
      tags: package,cli,cmdline

    - import_tasks: tasks/package/hardware.yml
      tags: package,hw,hardware

    - import_tasks: tasks/config/power.yml
      tags: config,power

    - import_tasks: tasks/config/peripherals.yml
      tags: config,peripherals

    - import_tasks: tasks/config/dotfiles.yml
      tags: config,dotfiles

    - import_tasks: tasks/package/tmux.yml
      tags: package,cli,cmdline,tmux

    - import_tasks: tasks/package/vim.yml
      tags: package,cli,cmdline,vim

    - import_tasks: tasks/package/docker.yml
      tags: package,cli,cmdline,docker

    - import_tasks: tasks/package/tlp.yml
      tags: package,cli,cmdline,tlp

    - name: GUI tasks
      when: user_desktop
      tags: gui,desktop,graphical
      block:
        - import_tasks: tasks/config/dock.yml
          tags: config,dock,appearance

        - import_tasks: tasks/config/wallpaper.yml
          tags: never,config,wallpaper,appearance

        - import_tasks: tasks/package/graphical.yml
          tags: never,package

        - import_tasks: tasks/package/virtualbox.yml
          tags: never,package,virtualbox


- hosts: all
  become: false
  tags: never,debug
  tasks:
    - import_tasks: tasks/debug.yml
