---
- hosts: all
  become: true

  pre_tasks:
    - import_tasks: tasks/package/update_cache.yml
      tags: package,update,upgrade,install

  tasks:
    - import_tasks: tasks/package/install.yml
      tags: package,install

    - import_tasks: tasks/config/provision.yml
      tags: config,provision

    - import_tasks: tasks/config/keyboard.yml
      tags: config,keyboard

    - import_tasks: tasks/config/dotfiles.yml
      tags: config,dotfiles

    - import_tasks: tasks/config/wallpaper.yml
      tags: config,wallpaper,aesthetic
