---
- hosts: all
  become: false
  tags: full,always
  pre_tasks:
    - import_tasks: tasks/requirements/facts.yml
      tags: requirements,facts

    - import_tasks: tasks/requirements/package_manager.yml
      tags: requirements,package-manager

    - import_tasks: tasks/requirements/dependencies.yml
      tags: requirements,dependencies

- hosts: all
  become: true
  tags: full
  pre_tasks:
    - import_tasks: tasks/config/provision.yml
      tags: config,provision

  tasks:
    - import_tasks: tasks/package/system.yml
      tags: package,cli,cmdline,system

    - import_tasks: tasks/package/pipx.yml
      tags: package,cli,cmdline,pipx

    - import_tasks: tasks/config/dotfiles.yml
      tags: config,dotfiles

    - import_tasks: tasks/config/locale.yml
      tags: config,locale

    - import_tasks: tasks/config/privacy.yml
      tags: config,privacy

    - import_tasks: tasks/config/power.yml
      tags: config,power

    - import_tasks: tasks/config/peripherals.yml
      tags: config,peripherals

    - import_tasks: tasks/config/default_apps.yml
      tags: config,default-apps

    - import_tasks: tasks/config/shortcuts.yml
      tags: config,shortcuts

    - import_tasks: tasks/config/software.yml
      tags: config,software

    - import_tasks: tasks/config/sound.yml
      tags: config,sound

    - import_tasks: tasks/config/media.yml
      tags: config,media

    - import_tasks: tasks/config/tiling.yml
      tags: config,tiling

    - import_tasks: tasks/config/multitasking.yml
      tags: config,multitasking

    - import_tasks: tasks/config/terminal.yml
      tags: config,terminal

    - import_tasks: tasks/package/ffmpeg.yml
      tags: package,cli,cmdline,ffmpeg

    - import_tasks: tasks/package/codecs.yml
      tags: package,cli,cmdline,codecs

    - import_tasks: tasks/package/tmux.yml
      tags: package,cli,cmdline,tmux

    - import_tasks: tasks/package/vim.yml
      tags: package,cli,cmdline,vim

    - import_tasks: tasks/package/neovim.yml
      tags: package,cli,cmdline,neovim,nvim

    - import_tasks: tasks/package/pyenv.yml
      tags: package,cli,cmdline,pyenv

    - import_tasks: tasks/package/tlp.yml
      tags: package,cli,cmdline,tlp
      when:
        - ansible_distribution != "Pop!_OS"  # not recommended: https://support.system76.com/articles/battery/
        - ansible_distribution != "Fedora"   # not working: https://linrunner.de/tlp/installation/fedora.html

    - import_tasks: tasks/package/docker.yml
      tags: package,cli,cmdline,docker

    - import_tasks: tasks/package/1password-cli.yml
      tags: package,cli,cmdline,1password,1password-cli

    - import_tasks: tasks/package/syncthing.yml
      tags: package,cli,cmdline,syncthing

    - name: GUI tasks
      when: user_desktop
      tags: gui,desktop,graphical
      block:
        - import_tasks: tasks/config/dock.yml
          tags: config,dock

        - import_tasks: tasks/config/appearance.yml
          tags: never,config,appearance

        - import_tasks: tasks/config/icon.yml
          tags: never,config,icon

        - import_tasks: tasks/package/gnome-extensions.yml
          tags: never,package,gnome-extensions,gnome-shell-extensions

        - import_tasks: tasks/config/extensions.yml
          tags: never,config,extensions

        - import_tasks: tasks/package/flatpak.yml
          tags: never,package,flatpak

        - import_tasks: tasks/package/virtualbox.yml
          tags: never,package,virtualbox

        - import_tasks: tasks/package/virtualbox-extpack.yml
          tags: never,package,virtualbox-extpack

        # cli but depends on virtualbox
        - import_tasks: tasks/package/vagrant.yml
          tags: never,package,vagrant

        - import_tasks: tasks/package/vscode.yml
          tags: never,package,vscode

        - import_tasks: tasks/package/wireshark.yml
          tags: never,package,wireshark

        - import_tasks: tasks/package/insync.yml
          tags: never,package,insync

    - import_tasks: tasks/config/autostart.yml
      tags: config,autostart

- hosts: all
  become: false
  tags: never,debug
  tasks:
    - import_tasks: tasks/debug.yml
