---
- hosts: localhost  # this will target localhost
  connection: local  # ansible usually uses ssh, but with this it will use local connection
  become: true  # enables sudo

  tasks:
    - name: install packages
      package:
        name:
          - git

    - name: hello world
      debug:
        msg: "hello world"

    - name: copy provision to /usr/local/sbin
      copy:
        src: provision
        dest: /usr/local/sbin/provision
        owner: root
        group: root
        mode: 755

    - name: Clone dotfiles to ~/.dotfiles
      become_user: paulo
      git:
        repo: https://github.com/pauloromeira/dotfiles.git
        dest: ~/.dotfiles
