---
- name: Facts > user
  set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop:
    - { key: "user_id", value: "{{ ansible_user_id }}" }
    - { key: "user_dir", value: "{{ ansible_user_dir }}" }
    - { key: "user_desktop", value: "{{ lookup('env','XDG_CURRENT_DESKTOP').split(':') | last | lower | trim }}" }
