---
- name: Requirements > apt > update cache
  become: true
  tags: apt
  apt:
    update_cache: true
  changed_when: false
  when: ansible_pkg_mgr == "apt"

- name: Requirements > Install system requirements
  become: true
  package:
    name: "{{ item }}"
  loop:
    - git

- name: Requirements > Install pip requirements
  pip:
    name: psutil
    extra_args: --user

- name: Requirements > Gather extra facts > os-release
  set_fact:
    "os_release_{{ item.split('=', 1)[0] | lower }}": "{{ item.split('=', 1)[1] }}"
  when: "'=' in item"
  loop: "{{ lookup('file', '/etc/os-release').splitlines() }}"

- name: Requirements > Gather extra facts
  set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop:
    - { key: "user_id", value: "{{ ansible_user_id }}" }
    - { key: "user_dir", value: "{{ ansible_user_dir }}" }
    - { key: "user_desktop", value: "{{ lookup('env','XDG_CURRENT_DESKTOP') | split(':') | last | lower | trim }}" }
    - { key: "dpkg_arch", value: "{{ dpkg_arch_mapping[ansible_architecture] }}" }
    - { key: "os_id", value: "{{ os_release_id | lower }}" }
