---
- name: Style > Set to dark
  tags: style,color-scheme
  become_user: "{{ user_id }}"
  when: user_desktop == "gnome"
  dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

- name: Background > Copy wallpaper file
  tags: background,wallpaper
  copy:
    src: files/config/wallpaper.png
    dest: /usr/share/backgrounds/wallpaper.png
    owner: root
    group: root

- name: Background > Set wallpaper
  tags: background,wallpaper
  when: user_desktop == "gnome"
  become_user: "{{ user_id }}"
  dconf:
    key: "/org/gnome/desktop/background/{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "picture-uri", value: "'file:///usr/share/backgrounds/wallpaper.png'" }
    - { key: "picture-uri-dark", value: "'file:///usr/share/backgrounds/wallpaper.png'" }
    - { key: "picture-options", value: "'zoom'" }
