---
# To get all dconf settings run: `dconf dump /`

- name: Dock > configure dock (gnome)
  tags: gnome
  when: desktop == "gnome"
  become_user: paulo
  block:
    - name: Dock > set position to bottom
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
        value: "'BOTTOM'"

    - name: Dock > disable extend height
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/extend-height"
        value: "false"

    - name: Dock > disable fixed
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
        value: "false"

    - name: Dock > enable intelligent hide
      dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/intellihide"
        value: "true"
