---
- name: Dock > Dash to dock > Install gnome extension
  import_role:
    name: add_gnome_extension
  vars:
    ext_uuid: dash-to-dock@micxgx.gmail.com
    ext_name: Dash to dock

# To get all dconf settings run: `dconf dump /`
- name: Dock > dconf setup (gnome)
  tags: gnome
  when: user_desktop == "gnome"
  become_user: "{{ user_id }}"
  dconf:
    key: "{{ '/org/gnome/shell/extensions/dash-to-dock/' + item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "dock-position", value: "'BOTTOM'" }
    - { key: "extend-height", value: "false" }
    - { key: "dock-fixed", value: "false" }
    - { key: "intellihide", value: "true" }
    - { key: "custom-theme-shrink", value: "true" }
    - { key: "customize-alphas", value: "true" }
    - { key: "max-alpha", value: "0.87" }
    - { key: "min-alpha", value: "0.87" }
    - { key: "transparency-mode", value: "'DYNAMIC'" }
    - { key: "show-trash", value: "false" }

- name: Dock > Set favorite apps (gnome)
  tags: gnome
  when: user_desktop == "gnome"
  become_user: "{{ user_id }}"
  dconf:
    key: /org/gnome/shell/favorite-apps
    value: [
      'org.chromium.Chromium.desktop',
      'org.gnome.Terminal.desktop',
      'org.gnome.Nautilus.desktop',
      'com.getpostman.Postman.desktop',
      'com.spotify.Client.desktop',
      'firefox.desktop',
      'io.dbeaver.DBeaverCommunity.desktop',
      'virtualbox.desktop',
    ]
