---
# To get all dconf settings run: `dconf dump /`
- name: Dock > dconf setup (gnome)
  tags: gnome
  when: desktop == "gnome"
  become_user: paulo
  dconf:
    key: "{{ '/org/gnome/shell/extensions/dash-to-dock/' + item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "dock-position", value: "'BOTTOM'" }
    - { key: "extend-height", value: "false" }
    - { key: "dock-fixed", value: "false" }
    - { key: "intellihide", value: "true" }
