---
# To get all dconf settings run: `dconf dump /`
- name: Dock > dconf setup (gnome)
  tags: gnome
  when: user_desktop == "gnome"
  become_user: "{{ user_id }}"
  dconf:
    key: "{{ '/org/gnome/shell/extensions/dash-to-dock/' + item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "dock-position", value: "'BOTTOM'" }
    - { key: "extend-height", value: "false" }
    - { key: "dock-fixed", value: "false" }
    - { key: "intellihide", value: "true" }
    - { key: "custom-theme-shrink", value: "true" }
    - { key: "customize-alphas", value: "true" }
    - { key: "max-alpha", value: "0.8" }
    - { key: "min-alpha", value: "0.8" }
    - { key: "transparency-mode", value: "'DYNAMIC'" }
    - { key: "show-trash", value: "false" }
