---
# To get all dconf settings run: `dconf dump /`
- name: Dock > Dash to dock > dconf setup
  tags: gnome
  when: user_desktop == "gnome"
  become_user: "{{ user_id }}"
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "dock-position", value: "'BOTTOM'" }
    - { key: "extend-height", value: "false" }
    - { key: "dock-fixed", value: "false" }
    - { key: "intellihide", value: "true" }
    - { key: "intellihide-mode", value: "'ALL_WINDOWS'" }
    - { key: "custom-theme-shrink", value: "true" }
    - { key: "transparency-mode", value: "'FIXED'" }
    - { key: "background-opacity", value: "0.6" }
    - { key: "dash-max-icon-size", value: "48" }
    - { key: "show-mounts", value: "true" }
    - { key: "show-mounts-only-mounted", value: "true" }
    - { key: "show-trash", value: "true" }

- name: Dock > Set favorite apps
  tags: gnome
  when: user_desktop == "gnome"
  become_user: "{{ user_id }}"
  dconf:
    key: /org/gnome/shell/favorite-apps
    value:
      - 'chromium-browser.desktop'  # native
      - 'org.chromium.Chromium.desktop'  # flatpak
      - 'org.gnome.Terminal.desktop'
      - 'org.gnome.Nautilus.desktop'
      - 'com.spotify.Client.desktop'
      - 'firefox.desktop'
      - 'io.dbeaver.DBeaverCommunity.desktop'
      - 'virtualbox.desktop'
      - 'org.gnome.Calendar.desktop'
      - 'org.gnome.Software.desktop'
