---
- name: Dotfiles > Install requirements
  package:
    name: "{{ item }}"
  loop:
    - git
    - stow

- name: Dotfiles > clone and configure repository
  become_user: "{{ user_id }}"
  block:
    - name: Dotfiles > clone repository via https
      git:
        repo: "{{ git_https_url }}/{{ dotfiles_repo }}.git"
        dest: "{{ dotfiles_dir }}"
        update: no

    - name: Dotfiles > set push ssh url
      git_config:
        repo: "{{ dotfiles_dir }}"
        scope: local
        name: remote.origin.pushurl
        value: "{{ git_ssh_url }}/{{ dotfiles_repo }}.git"

- name: Dotfiles > find packages and create symlinks
  become_user: "{{ user_id }}"
  tags: symlinks
  block:
    - name: Dotfiles > find packages
      find:
        paths: "{{ dotfiles_dir }}"
        recurse: no
        file_type: directory
      register: dotfiles

    - name: Dotfiles > stow > create symlinks
      command:
        chdir: "{{ dotfiles_dir }}"
        cmd: stow --no-folding --adopt --verbose=2 "{{ item }}"
      register: stow_dotfiles
      changed_when: stow_dotfiles.stderr | regex_search('(?m)^LINK')
      with_items: "{{ dotfiles.files | map(attribute='path') | map('basename') }}"
