---
# TODO: Migrate dotfiles and change from dotfiles2 to dotfiles
- name: Dotfiles > clone and setup repository
  become_user: paulo
  block:
    - name: Dotfiles > clone to ~/.dotfiles2/ (temporary)
      git:
        repo: https://github.com/pauloromeira/dotfiles2.git
        dest: ~/.dotfiles2

    - name: Dotfiles > set ssh push url
      git_config:
        repo: ~/.dotfiles2
        scope: local
        name: remote.origin.pushurl
        value: git@github.com:pauloromeira/dotfiles2.git

- name: Dotfiles > create symlinks
  tags: symlinks
  become_user: paulo
  command:
    chdir: ~/.dotfiles2
    cmd: stow --dotfiles --verbose=2 "{{ item }}"
  register: stow_dotfiles
  changed_when: stow_dotfiles.stderr | regex_search('(?m)^LINK')
  loop:
    - git
    - pdb
    - tmux
    - vim
