---
- name: Dotfiles > clone to ~/.dotfiles/
  become_user: paulo
  git:
    repo: https://github.com/pauloromeira/dotfiles.git
    dest: ~/.dotfiles

- name: Dotfiles > set push ssh url
  become_user: paulo
  git_config:
    repo: ~/.dotfiles
    scope: local
    name: remote.origin.pushurl
    value: git@github.com:pauloromeira/dotfiles.git
