---
# To get all dconf settings run: `dconf dump /`
- name: Keyboard > swap ctrl/caps and set right alt as compose key (dconf)
  become_user: paulo
  dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['ctrl:swapcaps', 'compose:ralt']"

# TODO: restart X server
- name: Keyboard > swap ctrl/caps and set right alt as compose key (xorg.conf)
  copy:
    src: files/config/keyboard.conf
    dest: /usr/share/X11/xorg.conf.d/10-keyboard.conf
    owner: root
    group: root
    mode: 0644
