---
- name: Clock > Set format to 24h
  tags: gnome
  when: user_desktop == "gnome"
  become_user: "{{ user_id }}"
  dconf:
    key: "{{ item }}/clock-format"
    value: "'24h'"
  loop:
    - /org/gnome/desktop/interface
    - /org/gtk/settings/file-chooser

- name: Clock > Show week day
  tags: gnome
  when: user_desktop == "gnome"
  become_user: "{{ user_id }}"
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "true"

- name: Formats > Set formats to UK
  tags: gnome
  when: user_desktop == "gnome"
  become_user: "{{ user_id }}"
  dconf:
    key: "/system/locale/region"
    value: "'en_GB.UTF-8'"
