---
- name: Media > disable auto-mount
  tags: gnome
  when: user_desktop == "gnome"
  become_user: "{{ user_id }}"
  dconf:
    key: "{{ '/org/gnome/desktop/media-handling/' + item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "automount", value: "false" }
    - { key: "automount-open", value: "false" }
