---
# To get all dconf settings run: `dconf dump /`
- name: Peripherals > Keyboard > swap ctrl/caps and set right alt as compose key (gnome)
  tags: gnome
  become_user: "{{ user_id }}"
  dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['ctrl:swapcaps', 'compose:ralt']"
  when: user_desktop == "gnome"

# TODO: restart X server (handler)
- name: Peripherals > Keyboard > swap ctrl/caps and set right alt as compose key (xorg.conf)
  tags: xfce
  copy:
    src: files/config/keyboard.conf
    dest: /usr/share/X11/xorg.conf.d/10-keyboard.conf
    owner: root
    group: root
    mode: 0644
  when: user_desktop != "gnome"

- name: Peripherals > Touchpad
  tags: gnome
  become_user: "{{ user_id }}"
  when: user_desktop == "gnome"
  dconf:
    key: "{{ '/org/gnome/desktop/peripherals/touchpad/' + item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "natural-scroll", value: "true" }
    - { key: "tap-to-click", value: "true" }
    - { key: "two-finger-scrolling-enabled", value: "true" }
