---
- name: Provision > clone and configure repository
  become_user: "{{ user_id }}"
  block:
    - name: Provision > clone repository via https
      git:
        repo: "{{ git_https_url }}/{{ provision_repo }}.git"
        dest: "{{ provision_dir }}"
        update: false

    - name: Provision > set push ssh url
      git_config:
        repo: "{{ provision_dir }}"
        scope: local
        name: remote.origin.pushurl
        value: "{{ git_ssh_url }}/{{ provision_repo }}.git"

- name: Provision > setup provision command
  become_user: "{{ user_id }}"
  block:
    - name: Provision > create dir ~/.local/bin/
      file:
        path: "{{ user_dir }}/.local/bin/"
        state: directory

    - name: Provision > create symlink on ~/.local/bin/provision
      file:
        src: "{{ provision_dir }}/provision.sh"
        dest: "{{ user_dir }}/.local/bin/provision"
        state: link
        force: true
