---
- name: Provision > clone repository
  become_user: "{{ user_id }}"
  block:
    - name: Provision > clone to ~/.provision/
      git:
        repo: "https://github.com/{{ github_user }}/provision.git"
        dest: "{{ provision_dir }}"
        update: no

    - name: Provision > set ssh push url
      git_config:
        repo: "{{ provision_dir }}"
        scope: local
        name: remote.origin.pushurl
        value: "git@github.com:{{ github_user }}/provision.git"

- name: Provision > setup provision command
  become_user: "{{ user_id }}"
  block:
    - name: Provision > create dir ~/.local/bin/
      file:
        path: "{{ user_dir }}/.local/bin/"
        state: directory

    - name: Provision > create hard link on ~/.local/bin/provision
      file:
        src: "{{ provision_dir }}/provision.sh"
        dest: "{{ user_dir }}/.local/bin/provision"
        state: hard
        force: yes
