---
- name: Provision > setup provision command
  become_user: paulo
  block:
    - name: Provision > create ~/.local/bin/
      file:
        path: ~/.local/bin/
        state: directory

    - name: Provision > copy provision.sh to ~/.local/bin/provision
      copy:
        src: provision.sh
        dest: ~/.local/bin/provision
        mode: 0775
