---
- name: Provision > clone repository
  become_user: paulo
  block:
    - name: Provision > clone to ~/.provision/
      git:
        repo: https://github.com/pauloromeira/provision.git
        dest: ~/.provision
        update: no

    - name: Provision > set ssh push url
      git_config:
        repo: ~/.provision
        scope: local
        name: remote.origin.pushurl
        value: git@github.com:pauloromeira/provision.git

- name: Provision > setup provision command
  become_user: paulo
  block:
    - name: Provision > create dir ~/.local/bin/
      file:
        path: ~/.local/bin/
        state: directory

    - name: Provision > create hard link on ~/.local/bin/provision
      file:
        src: ~/.provision/provision.sh
        dest: ~/.local/bin/provision
        state: hard
        force: yes
