---
- name: Sound > dconf setup (gnome)
  tags: gnome
  when: user_desktop == "gnome"
  become_user: "{{ user_id }}"
  dconf:
    key: "/org/gnome/desktop/sound/{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "allow-volume-above-100-percent", value: "true" }

# NOT NEEDED - for fedora and probably gnome 45
- name: Sound > Gnome Extension > Sount Input & Output Device Chooser
  tags: gnome
  when: user_desktop == "gnome"
  become_user: "{{ user_id }}"
  dconf:
    key: "/org/gnome/shell/extensions/sound-output-device-chooser/{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "hide-menu-icons", value: "true" }
