---
- name: Wallpaper > copy file
  copy:
    src: files/wallpaper.png
    dest: /usr/share/backgrounds/wallpaper.png
    owner: root
    group: root

- name: Wallpaper > set light background
  become_user: paulo
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/wallpaper.png'"

- name: Wallpaper > set dark background
  become_user: paulo
  dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/wallpaper.png'"

- name: Wallpaper > set zoom position
  become_user: paulo
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
