---
- name: Wallpaper > copy file
  copy:
    src: files/config/wallpaper.png
    dest: /usr/share/backgrounds/wallpaper.png
    owner: root
    group: root

- name: Wallpaper > dconf setup (gnome)
  tags: gnome
  when: desktop == "gnome"
  become_user: paulo
  block:
    - name: Wallpaper > set light background
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/wallpaper.png'"

    - name: Wallpaper > set dark background
      dconf:
        key: "/org/gnome/desktop/background/picture-uri-dark"
        value: "'file:///usr/share/backgrounds/wallpaper.png'"

    - name: Wallpaper > set zoom position
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"
