---
- name: Wallpaper > copy file
  copy:
    src: files/config/wallpaper.png
    dest: /usr/share/backgrounds/wallpaper.png
    owner: root
    group: root

- name: Wallpaper > dconf setup (gnome)
  tags: gnome
  when: desktop == "gnome"
  become_user: "{{ user_id }}"
  dconf:
    key: "{{ '/org/gnome/desktop/background/' + item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "picture-uri", value: "'file:///usr/share/backgrounds/wallpaper.png'" }
    - { key: "picture-uri-dark", value: "'file:///usr/share/backgrounds/wallpaper.png'" }
    - { key: "picture-options", value: "'zoom'" }
