---
# References:
#   - https://discourse.gnome.org/t/enable-gnome-extensions-without-session-restart/7936/4
#   - https://gist.github.com/alexs77/b41f4140388f8a23e3013ef3226fc46a
#   - https://www.reddit.com/r/gnome/comments/rbl85n/installing_gnomeshell_extensions_on_command_line/
- name: Check mandatory variables are defined
  assert:
    that:
      - ext_uuid is defined

- name: Get gnome-shell version
  command: gnome-shell --version
  register: shell_version_cmd
  changed_when: false

- name: Set gnome-shell version
  set_fact: 
    shell_version: "{{ shell_version_cmd.stdout | split | last }}"

- name: "{{ ext_name }} > Query extension by uuid"
  uri:
    url: "https://extensions.gnome.org/extension-query/?shell_version={{ shell_version }}&uuid={{ ext_uuid }}"
    return_content: true
  register: query_response

- name: "{{ ext_name }} > Select extension by uuid"
  set_fact:
    info: "{{ query_response.json.extensions | selectattr('uuid', 'equalto', ext_uuid) | first }}"

- name: "{{ ext_name }} > Select extension version that matches shell version"
  set_fact:
    version: "{{ info.shell_version_map | dict2items | selectattr('key', 'version', shell_version, '<=') | last }}"

- name: "{{ ext_name }} > Version info"
  debug:
    msg: "shell version: {{ shell_version }}, compatible extension version: {{ version.key }}"

- name: "{{ ext_name }} > Set version_tag"
  set_fact:
    version_tag: "{{ version.value.pk }}"

- name: "{{ ext_name }} > Download zip package"
  become_user: "{{ user_id }}"
  get_url:
    url: "https://extensions.gnome.org/download-extension/{{ ext_uuid }}.shell-extension.zip?version_tag={{ version_tag }}"
    dest: "/tmp/"
  register: download_response
  changed_when: false

- name: "{{ ext_name }} > Install extension"
  become_user: "{{ user_id }}"
  command: gnome-extensions install "{{ download_response.dest }}"
  register: install_result
  failed_when: "install_result.rc != 0 and 'exists' not in install_result.stderr"
  changed_when: install_result.rc == 0

- name: "{{ ext_name }} > Enable extension"
  become_user: "{{ user_id }}"
  command: gnome-extensions enable "{{ ext_uuid }}"
  changed_when: false
  when: install_result.changed

- name: "{{ ext_name }} > Manual step"
  debug:
    msg: "For the changes to take effect, GNOME Shell needs to be restarted (Alt+F2 r <enter>)"
  when: install_result.changed
