---
- name: Package manager > Dnf > Config
  tags: dnf
  become: true
  when: ansible_pkg_mgr == "dnf"
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
  loop:
    - { key: "fastestmirror", value: true }
    - { key: "defaultyes", value: true }
    - { key: "max_parallel_downloads", value: 10 }

- name: Package manager > Dnf > Configure RPM Fusion repos (fedora)
  tags: rpmfusion
  become: true
  when: os_id == "fedora"
  block:
    - name: Package manager > Dnf > Install RPM Fusion GPG key (fedora)
      rpm_key:
        key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-{{ item }}-fedora-2020"
        state: present
      loop:
        - free
        - nonfree

    - name: Package manager > Dnf > Add RPM Fusion repos (fedora)
      dnf:
        name: "https://mirrors.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      loop:
        - free
        - nonfree

- name: Package manager > Apt > update cache
  tags: apt
  become: true
  apt:
    update_cache: true
  changed_when: false
  when: ansible_pkg_mgr == "apt"

- name: Package manager > Dnf > update cache
  tags: dnf
  become: true
  dnf:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "dnf"
