---
# References:
#   - https://support.1password.com/install-linux/
#   - https://wiki.debian.org/DebianRepository/UseThirdParty
- name: 1Password > Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - gpg

- name: 1Password > Add asc key (armored)
  get_url:
    url: https://downloads.1password.com/linux/keys/1password.asc
    dest: /usr/share/keyrings/1password-archive-keyring.asc
  register: asc_key

- name: 1Password > Add gpg key (dearmor)
  command: >
    gpg
    --yes
    --no-default-keyring
    --output /usr/share/keyrings/1password-archive-keyring.gpg
    --dearmor "{{ asc_key.dest }}"
  when: asc_key.changed

- name: 1Password > Add apt repository
  apt_repository:
    repo: "deb [arch={{ dpkg_arch }} signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/{{ dpkg_arch }} stable main"
    filename: 1password
    state: present
    update_cache: true

- name: 1Password > Install 1Password CLI
  apt:
    name: 1password-cli
    state: present
