---
# References:
#   - https://support.1password.com/install-linux/
- name: 1Password > Add apt repository
  import_role:
    name: apt_add_repository
  vars:
    repo_name: 1password
    repo: "deb https://downloads.1password.com/linux/debian/{{ dpkg_arch }} stable main"
    key_url: https://downloads.1password.com/linux/keys/1password.asc
    dearmor: true

- name: 1Password > Install 1Password CLI
  apt:
    name: 1password-cli
    state: present
