---
# References:
#   - https://support.1password.com/install-linux/
- name: 1Password > Add apt repository (apt)
  import_role:
    name: add_apt_repository
  vars:
    repo_name: 1password
    repo_source: "deb https://downloads.1password.com/linux/debian/{{ dpkg_arch }} stable main"
    key_url: https://downloads.1password.com/linux/keys/1password.asc
  when: ansible_pkg_mgr == "apt"

- name: 1Password > Add yum repository (dnf)
  yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
  when: ansible_pkg_mgr == "dnf"

- name: 1Password > Install 1Password CLI
  package:
    name: 1password-cli
    state: present
