---
# References:
#   - http://asdf-vm.com/guide/getting-started.html
- name:  Asdf > Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - git

- name:  Asdf > Get latest release
  uri:
    url: https://github.com/asdf-vm/asdf/releases/latest
    method: HEAD
    follow_redirects: no
  register: asdf_release_response
  failed_when: asdf_release_response.status != 302

- name: Asdf > Set latest release
  set_fact:
    asdf_release: "{{ asdf_release_response.location.split('/') | last }}"

- name: Asdf > Latest release
  debug:
    var: asdf_release

- name: Asdf > Clone repository
  become_user: "{{ user_id }}"
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ asdf_dir }}"
    version: "{{ asdf_release }}"
    depth: 1

- name: Asdf > Clone plugins repositories
  become_user: "{{ user_id }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ asdf_dir }}/plugins/{{ item.name }}"
    depth: 1
  loop:
    - name: aws-vault
      repo: https://github.com/karancode/asdf-aws-vault.git
