---
# References:
#   - http://asdf-vm.com/guide/getting-started.html
- name:  Asdf > Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - git

- name:  Asdf > Get latest release
  uri:
    url: https://github.com/asdf-vm/asdf/releases/latest
    method: HEAD
    follow_redirects: no
  register: asdf_release_response
  failed_when: asdf_release_response.status != 302

- name: Asdf > Set latest release
  set_fact:
    asdf_release: "{{ asdf_release_response.location.split('/') | last }}"

- name: Asdf > Latest release
  debug:
    var: asdf_release

- name: Asdf > Clone repository
  become_user: "{{ user_id }}"
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ asdf_dir }}"
    version: "{{ asdf_release }}"
    depth: 1

- name: Asdf > Set asdf plugins
  set_fact:
    asdf_plugins:
      - name: kubectl
        repo: https://github.com/asdf-community/asdf-kubectl.git
        version: latest
      - name: aws-vault
        repo: https://github.com/karancode/asdf-aws-vault.git
        version: latest

- name: Asdf > Clone plugins repositories
  become_user: "{{ user_id }}"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ asdf_dir }}/plugins/{{ item.name }}"
    depth: 1
  with_items: "{{ asdf_plugins }}"

- name: Asdf > Install plugins latest versions
  become_user: "{{ user_id }}"
  command: "{{ asdf_dir }}/bin/asdf install {{ item.name }} {{ item.version }}"
  register: asdf_plugins_installed
  changed_when: "'already installed' not in asdf_plugins_installed.stdout"
  with_items: "{{ asdf_plugins }}"

- name: Asdf > Set plugins global versions
  become_user: "{{ user_id }}"
  command: "{{ asdf_dir }}/bin/asdf global {{ item.item.name }} {{ item.item.version }}"
  when: item.changed
  with_items: "{{ asdf_plugins_installed.results }}"
