---
# References:
#   - https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html
- name: Install AWS Session Manager plugin
  apt:
    deb: "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_{{ '64bit' if ansible_architecture == 'x86_64' else '32bit' }}/session-manager-plugin.deb"
