---
- name: Package > CLI > install provision requirements
  package:
    name: "{{ item }}"
  loop:
    - git
    - stow

- name: Package > CLI > pip > install provision requirements
  become_user: "{{ user_id }}"
  pip:
    name: psutil
    extra_args: --user

- name: Package > CLI > install utilities
  package:
    name: "{{ item }}"
  loop:
    - bat
    - curl
    - gcc
    - htop
    - make
    - openssh-client
    - silversearcher-ag
    - sqlite3
    - tree
    - unrar
    - unzip
    - wget
    - xsel

- name: Package > CLI > pip > install pipx
  tags: pipx
  become_user: "{{ user_id }}"
  pip:
    name: pipx
    extra_args: --user

- name: Package > CLI > pipx > install packages
  tags: pipx
  become_user: "{{ user_id }}"
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - awscli
    - docker-compose
    - dvc
    - faker
    - flake8
    - ipython
    - magic-wormhole
    - mitmproxy
    - notebook
    - ranger-fm
    - tmuxp
    - youtube-dl

- name: Package > CLI > pipx > inject into ipython
  tags: pipx
  become_user: "{{ user_id }}"
  community.general.pipx:
    name: ipython
    inject_packages: "{{ item }}"
    state: inject
  loop:
    - arrow
    - ipdb
    - jmespath
    - openpyxl
    - pandas
    - parsel
    - python-slugify
    - requests
    - scrapy
    - tenacity
