---
- name: Package > CLI > install system packages
  package:
    name:
      - git
      - curl
      - stow

- name: Package > CLI > pip > install ansible requirements
  become_user: paulo
  pip:
    name: psutil

- name: Package > CLI > pip > install pipx
  tags: pipx
  become_user: paulo
  pip:
    name: pipx
    extra_args: --user

- name: Package > CLI > pipx > install mitmproxy
  tags: pipx
  become_user: paulo
  community.general.pipx:
    name: mitmproxy
