---
- name: Package > CLI > install system packages
  package:
    name:
      - git
      - curl
      - stow

- name: Package > CLI > pip > install ansible requirements
  become_user: paulo
  pip:
    name: psutil

- name: Package > CLI > pipx > install in virtualenv
  tags: pipx
  become_user: paulo
  pip:
    name: pipx
    virtualenv: ~/.local/venvs/pipx
    virtualenv_command: "{{ global_python_interpreter }} -m venv"

- name: Package > CLI > pipx > create symlink in ~/.local/bin
  tags: pipx
  become_user: paulo
  file:
    src: ~/.local/venvs/pipx/bin/pipx
    dest: ~/.local/bin/pipx
    state: link

- name: Package > CLI > pipx > install mitmproxy
  tags: pipx
  become_user: paulo
  community.general.pipx:
    name: mitmproxy
    executable: /home/paulo/.local/bin/pipx
