---
- name: Package > CLI > install system packages
  package:
    name:
      - git
      - curl
      - stow
      - vim-gtk
      - tmux

- name: Package > CLI > pip > install ansible requirements
  become_user: paulo
  pip:
    name: psutil
    extra_args: --user

- name: Package > CLI > pip > install pipx
  tags: pipx
  become_user: paulo
  pip:
    name: pipx
    extra_args: --user

- name: Package > CLI > pipx > install packages
  tags: pipx,install
  become_user: paulo
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - mitmproxy
    - ranger-fm
    - ipython
    - dvc

- name: Package > CLI > pipx > inject into ipython
  tags: pipx,install
  become_user: paulo
  community.general.pipx:
    name: ipython
    inject_packages:
      - requests
      - parsel
    state: inject
