---
# References:
#   - https://rpmfusion.org/Howto/Multimedia

# WARN: ffmpeg task is a requirement for fedora (with allowerasing)
# TODO: ass ffmpeg task as dependency or something like that

- name: Codecs > @multimedia > Install group package (dnf)
  dnf:
    name: "@multimedia"
    state: latest
    install_weak_deps: false
    exclude: "PackageKit-gstreamer-plugin"
  when: ansible_pkg_mgr == "dnf"

- name: Codecs > @sound-and-video > Install group package (dnf)
  dnf:
    name: "@sound-and-video"
    state: latest
  when: ansible_pkg_mgr == "dnf"
