---
# References:
#   - https://rpmfusion.org/Howto/Multimedia
- name: Codecs > Remove conflicting packages (dnf)
  dnf:
    name: ffmpeg-free
    state: absent
  when: ansible_pkg_mgr == "dnf"

- name: Codecs > @multimedia > Install group package (dnf)
  dnf:
    name: "@multimedia"
    state: latest
    install_weak_deps: false
    exclude: "PackageKit-gstreamer-plugin"
  when: ansible_pkg_mgr == "dnf"

- name: Codecs > @sound-and-video > Install group package (dnf)
  dnf:
    name: "@sound-and-video"
    state: latest
  when: ansible_pkg_mgr == "dnf"
