---
# References:
#   - https://docs.docker.com/engine/install/ubuntu/
#   - https://docs.docker.com/engine/install/linux-postinstall/
- name: Docker > Uninstall old versions
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Docker > Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Docker > Add apt repository
  import_role:
    name: apt_add_repository
  vars:
    repo_name: docker
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    key_url: https://download.docker.com/linux/ubuntu/gpg

- name: Docker > Install Docker Engine
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Docker > Ensure docker group exists
  group:
    name: docker
    state: present

- name: Docker > Add user to docker group
  user:
    name: "{{ user_id }}"
    groups: docker
    append: true

- name: Docker > Ensure service started
  service:
    name: docker
    state: started
    enabled: true
