---
- name: FFmpeg > Configure RPM Fusion free repos (fedora)
  tags: rpmfusion-free,rpmfusion
  when: os_id == "fedora"
  block:
    - name: FFmpeg > Install RPM Fusion free GPG key (fedora)
      rpm_key:
        key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
        state: present

    - name: FFmpeg > Add RPM Fusion free repos (fedora)
      dnf:
        name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: FFmpeg > Install
  package:
    name: ffmpeg
  when: ansible_pkg_mgr != "dnf"

- name: FFmpeg > Install (dnf)
  dnf:
    name: ffmpeg
    allowerasing: true
  when: ansible_pkg_mgr == "dnf"
