---
- name: Package > GUI > flatpak > install
  tags: flatpak
  package:
    name: flatpak
    state: present

- name: Package > GUI > flatpak > add flathub remote
  tags: flatpak,flathub
  become_user: "{{ user_id }}"
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Package > GUI > flatpak > install packages
  tags: flatpak
  become_user: "{{ user_id }}"
  flatpak:
    name: "{{ item }}"
  loop:
    - com.github.johnfactotum.Foliate
    - com.spotify.Client
    - io.dbeaver.DBeaverCommunity
    - org.chromium.Chromium
    - org.gimp.GIMP
    - org.remmina.Remmina
    - org.videolan.VLC
    - com.bitwig.BitwigStudio
    # - com.getpostman.Postman
    # - com.google.AndroidStudio
    # - org.gnome.Cheese
