---
# https://extensions.gnome.org/extension/307/dash-to-dock/
- name: Gnome Extension > Dash to Dock > Install
  tags: dash-to-dock
  when: user_desktop == "gnome"
  block:
    - name: Gnome Extension > Dash to Dock > Install
      import_role:
        name: add_gnome_extension
      vars:
        ext_uuid: dash-to-dock@micxgx.gmail.com
        ext_name: Dash to Dock
      when: ansible_pkg_mgr != "dnf"

    - name: Gnome Extension > Dash to Dock > Install (dnf)
      dnf:
        name: gnome-shell-extension-dash-to-dock
      when: ansible_pkg_mgr == "dnf"

- name: Gnome Extension > Pop Shell > Install (dnf)
  tags: pop-shell
  dnf:
    name: "{{ item }}"
  loop:
    - xprop
    - gnome-shell-extension-pop-shell
  when: user_desktop == "gnome" and ansible_pkg_mgr == "dnf"

# https://extensions.gnome.org/extension/517/caffeine/
- name: Gnome Extension > Caffeine > Install
  tags: caffeine
  when: user_desktop == "gnome"
  block:
    - name: Gnome Extension > Caffeine > Install
      import_role:
        name: add_gnome_extension
      vars:
        ext_uuid: caffeine@patapon.info
        ext_name: Caffeine
      when: ansible_pkg_mgr != "dnf"

    - name: Gnome Extension > Caffeine > Install (dnf)
      dnf:
        name: gnome-shell-extension-caffeine
      when: ansible_pkg_mgr == "dnf"

# NOT NEEDED - for fedora and probably gnome 45
# https://extensions.gnome.org/extension/906/sound-output-device-chooser/
- name: Gnome Extension > Sound Input & Output Device Chooser  > Install
  tags: sound-output-device-chooser
  import_role:
    name: add_gnome_extension
  vars:
    ext_uuid: sound-output-device-chooser@kgshank.net
    ext_name: Sound Input & Output Device Chooser
  when: user_desktop == "gnome" and ansible_pkg_mgr != "dnf"

# # ------------------------------------------------------------------- #
# # https://extensions.gnome.org/extension/1460/vitals/
# - name: Gnome Extension > Vitals > Install
#   tags: vitals
#   import_role:
#     name: add_gnome_extension
#   vars:
#     ext_uuid: Vitals@CoreCoding.com
#     ext_name: Vitals

# ERROR (not finding matching shell version)
# # https://extensions.gnome.org/extension/442/drop-down-terminal/
# - name: Gnome Extension > Drop Down Terminal > Install
#   tags: drop-down-terminal
#   import_role:
#     name: add_gnome_extension
#   vars:
#     ext_uuid: drop-down-terminal@gs-extensions.zzrough.org
#     ext_name: Drop Down Terminal
