---
- name: Package > GUI > flatpak > install
  tags: flatpak
  package:
    name: flatpak
    state: present

- name: Package > GUI > flatpak > add flathub remote
  tags: flatpak,flathub
  become_user: "{{ user_id }}"
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Package > GUI > flatpak > install packages
  tags: flatpak
  become_user: "{{ user_id }}"
  flatpak:
    method: user
    name: "{{ item }}"
  loop:
    - com.spotify.Client
    - com.google.Chrome
    - io.dbeaver.DBeaverCommunity
    - com.getpostman.Postman
    - org.remmina.Remmina
    - org.gnome.Cheese
    - org.gimp.GIMP
    - org.videolan.VLC
