---
- name: Package | GUI | install flatpak packages
  become_user: paulo
  flatpak:
    method: user
    name:
      - com.spotify.Client
      - com.google.Chrome
      - io.dbeaver.DBeaverCommunity
      - com.getpostman.Postman
      - org.remmina.Remmina
      - org.gnome.Cheese
