---
# References:
#   - https://www.insynchq.com/downloads
- name: Insync > Add apt repository
  import_role:
    name: apt_add_repository
  vars:
    repo_name: insync
    repo_source: "deb http://apt.insync.io/ubuntu {{ ansible_lsb.codename }} non-free contrib"
    key_id: ACCAF35C

- name: Insync > Install
  apt:
    name: insync
    state: present
