---
# References:
#   - https://github.com/trapexit/mergerfs#ubuntu
- name: MergerFS > Get latest release
  uri:
    url: https://github.com/trapexit/mergerfs/releases/latest
    method: HEAD
    follow_redirects: false
  register: mergerfs_release_response
  failed_when: mergerfs_release_response.status != 302

- name: MergerFS > Set latest release
  set_fact:
    mergerfs_release: "{{ mergerfs_release_response.location | split('/') | last }}"

- name: MergerFS > Latest release
  debug:
    var: mergerfs_release

- name: MergerFS > Install
  apt:
    deb: "https://github.com/trapexit/mergerfs/releases/download/{{ mergerfs_release }}/mergerfs_{{ mergerfs_release | trim('v') }}.ubuntu-{{ ansible_lsb.codename }}_{{ dpkg_arch }}.deb"
