---
# References:
#   - https://www.mono-project.com/download/stable/
#   - https://github.com/mono/mono
- name: Mono > Add apt repository
  import_role:
    name: add_apt_repository
  vars:
    repo_name: mono
    repo_source: "deb https://download.mono-project.com/repo/ubuntu stable-{{ ansible_lsb.codename }} main"
    key_id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: Mono > Install
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mono-complete
