---
- name: Pipx > Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

# https://github.com/mxmlnkn/ratarmount
- name: Pipx > ratarmount > dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - fuse
    - sqlite3
    - unar

- name: Pipx > Install
  tags: pipx
  become_user: "{{ user_id }}"
  pip:
    name: pipx
    extra_args: --user

- name: Pipx > Install packages
  tags: pipx
  become_user: "{{ user_id }}"
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - awscli
    - dvc
    - flake8
    - ipython
    - magic-wormhole
    - mitmproxy
    - notebook
    - ranger-fm
    - ratarmount
    - tmuxp
    - youtube-dl
    - eg
    - bpytop
    - pyxtermjs  # fully functional terminal in the browser
    - rich-cli
    - ffsubsync  # automatic synchronization of subtitles with video (dep: ffmpeg)

- name: Pipx > Inject into ipython
  tags: pipx
  become_user: "{{ user_id }}"
  community.general.pipx:
    name: ipython
    inject_packages: "{{ item }}"
    state: inject
  loop:
    - arrow
    - faker
    - ipdb
    - jmespath
    - openpyxl
    - pandas
    - parsel
    - python-slugify
    - requests
    - tenacity
