---
- name: Pipx > Install dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

- name: Pipx > Install
  tags: pipx
  become_user: "{{ user_id }}"
  pip:
    name: pipx
    extra_args: --user

- name: Pipx > Install packages
  tags: pipx
  become_user: "{{ user_id }}"
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - bpytop
    - eg
    - flake8
    - ipython
    - magic-wormhole
    - mitmproxy
    - notebook
    - ranger-fm
    - rich-cli
    - shell-functools
    - tmuxp
    - tox
    - yt-dlp
    - tldr  # similar to eg

- name: Pipx > Inject into ipython
  tags: pipx
  become_user: "{{ user_id }}"
  community.general.pipx:
    name: ipython
    inject_packages: "{{ item }}"
    state: inject
  loop:
    - arrow
    - faker
    - ipdb
    - jmespath
    - openpyxl
    - pandas
    - parsel
    - python-slugify
    - requests
    - tenacity
