---
# References:
#   - https://www.qbittorrent.org/download.php - Other Binary Packages
#   - https://launchpad.net/~qbittorrent-team/+archive/ubuntu/qbittorrent-stable
- name: qBittorrent > Add apt repository
  import_role:
    name: add_apt_repository
  vars:
    repo_name: qbittorrent
    repo_source: "deb https://ppa.launchpadcontent.net/qbittorrent-team/qbittorrent-stable/ubuntu {{ ansible_lsb.codename }} main"
    key_id: 401E8827DA4E93E44C7D01E6D35164147CA69FC4

- name: qBittorrent > Install
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - qbittorrent
