---
# References:
#   - https://docs.syncthing.net/intro/getting-started.html#installing
#   - https://apt.syncthing.net/
- name: Syncthing > Install requirements (apt)
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
  when: ansible_pkg_mgr == "apt"

- name: Syncthing > Add apt repository
  import_role:
    name: add_apt_repository
  vars:
    repo_name: syncthing
    repo_source: "deb https://apt.syncthing.net/ syncthing stable"
    key_url: https://syncthing.net/release-key.gpg
  when: ansible_pkg_mgr == "apt"

- name: Syncthing > Install
  package:
    name: "{{ item }}"
    state: present
  loop:
    - syncthing

- name: Syncthing > Ensure service started
  service:
    name: "syncthing@{{ user_id }}"
    state: started
    enabled: true
