---
- name: System > Install utilities
  package:
    name: "{{ item }}"
  loop:
    - bat
    - curl
    - ffmpeg
    - gcc
    - htop
    - jq
    - libnotify-bin
    - make
    - mkisofs
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - openssh-client
    - openvpn
    - silversearcher-ag
    - sqlite3
    - tree
    - unrar
    - unzip
    - wget
    - xsel
