---
- name: System > Install utilities
  package:
    name: "{{ item }}"
  loop:
    - bat
    - curl
    - ffmpeg
    - gcc
    - htop
    - jq
    - libnotify-bin
    - make
    - mkisofs
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - openssh-client
    - openvpn
    - pdftk
    - silversearcher-ag
    - sqlite3
    - tree
    - unrar
    - unzip
    - wget
    - xsel
    - solaar  # logitech unifying utility
    - at  # schedule commands to be executed at a particular time

- name: System > Disable autostart
  file:
    path: "/etc/xdg/autostart/{{ item }}.desktop"
    state: absent
  loop:
    - solaar
    - orca-autostart
