---
- name: System > Install utilities
  package:
    name: "{{ item }}"
  loop:
    - bat
    - curl
    - gcc
    - htop
    - jq
    - "{{ libnotify_package }}"
    - make
    - "{{ mkisofs_package }}"
    - openvpn
    - "{{ openssh_client_package }}"
    - pdftk
    - "{{ the_silver_searcher_package }}"
    - sqlite3
    - tree
    - unrar
    - unzip
    - wget
    - xsel
    - at
    - "{{ wireguard_package }}"
    # TODO: move to GUI
    - gnome-tweaks
    # - solaar  # logitech unifying utility
    # - network-manager-openvpn
    # - network-manager-openvpn-gnome
