---
- name: System > Configure RPM Fusion free repos (fedora)
  tags: rpmfusion-free,rpmfusion
  when: os_id == "fedora"
  block:
    - name: System > Install RPM Fusion free GPG key (fedora)
      rpm_key:
        key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
        state: present

    - name: System > Add RPM Fusion free repos (fedora)
      dnf:
        name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: System > Configure RPM Fusion nonfree repos (fedora)
  tags: rpmfusion-nonfree,rpmfusion
  when: os_id == "fedora"
  block:
    - name: System > Install RPM Fusion nonfree GPG key (fedora)
      rpm_key:
        key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
        state: present

    - name: System > Add RPM Fusion nonfree repos (fedora)
      dnf:
        name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: System > Install utilities
  package:
    name: "{{ item }}"
  loop:
    - bat
    - curl
    - ffmpeg
    - gcc
    - htop
    - jq
    - "{{ libnotify_package }}"
    - make
    - "{{ mkisofs_package }}"
    - openvpn
    - "{{ openssh_client_package }}"
    - pdftk
    - "{{ the_silver_searcher_package }}"
    - sqlite3
    - tree
    - unrar
    - unzip
    - wget
    - xsel
    - at
    - "{{ wireguard_package }}"
    # TODO: move to GUI
    - gnome-tweaks
    # - solaar  # logitech unifying utility
    # - network-manager-openvpn
    # - network-manager-openvpn-gnome

- name: System > Disable autostart
  file:
    path: "/etc/xdg/autostart/{{ item }}.desktop"
    state: absent
  loop:
    - solaar  # TODO: move to GUI
    - orca-autostart
