---
- name: Tmux > Install dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - xsel  # tmux-yank plugin

- name: Tmux > install tmux
  package:
    name: tmux

- name: Tmux > Tpm > tmux plugin manager
  tags: tpm
  become_user: "{{ user_id }}"
  block:
    - name: Tmux > Tpm > clone plugin manager
      git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: "{{ tmux_dir }}/plugins/tpm"

    - name: Tmux > Tpm > install plugins
      command: "{{ tmux_dir }}/plugins/tpm/bin/install_plugins"
      register: tmux_tpm_install
      changed_when: tmux_tpm_install.stdout | regex_search('(?m)^Installing')

    - name: Tmux plugins > tpm > debug
      debug:
        var: tmux_tpm_install.stdout
      changed_when: tmux_tpm_install.changed
