- name: Tmux > install tmux
  package:
    name: tmux

- name: Tmux > Tpm > tmux plugin manager
  tags: tpm
  become_user: paulo
  block:
    - name: Tmux > Tpm > clone plugin manager
      git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: ~/.tmux/plugins/tpm

    - name: Tmux > Tpm > install plugins
      command:
        cmd: ~/.tmux/plugins/tpm/bin/install_plugins
      register: tmux_tpm_install
      changed_when: tmux_tpm_install.stdout | regex_search('(?m)^Installing')

    - name: Tmux plugins > tpm > debug
      tags: debug
      debug:
        var: tmux_tpm_install.stdout
      changed_when: tmux_tpm_install.changed
