---
- name: Package > apt > update cache
  tags: apt
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == "apt"

- name: Package > pacman > update cache
  tags: pacman
  pacman:
    update_cache: yes
  when: ansible_pkg_mgr == "pacman"
