---
- name: Package > update apt cache
  tags: apt
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == "apt"

- name: Package > update pacman cache
  tags: pacman
  pacman:
    update_cache: yes
  when: ansible_pkg_mgr == "pacman"
