---
- name: Package | update apt cache
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == "apt"

- name: Package | update pacman cache
  pacman:
    update_cache: yes
  when: ansible_pkg_mgr == "pacman"
