---
- name: Package > Vim > install vim-gtk
  package:
    name: vim-gtk

- name: Package > Vim > install YouCompleteMe dependencies
  package:
    name: "{{ item }}"
  loop:
    - build-essential
    - cmake
    - python3-dev

- name: Package > Vim > install tagbar dependencies
  package:
    name: universal-ctags

- name: Package > Vim > create folders
  become_user: "{{ user_id }}"
  file:
    path: "{{ vim_dir }}/{{ item }}"
    state: directory
  loop:
    - "autoload"
    - "local"
    - "temp/undo"
    - "temp/backup"
    - "temp/swap"
    - "temp/view"
    - "temp/session"
    - "files/info"

- name: Package > Vim > download plugin manager
  become_user: "{{ user_id }}"
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ vim_dir }}/autoload/plug.vim"

- name: Vim > Plugins > clone forks
  become_user: "{{ user_id }}"
  git:
    repo: "{{ git_https_url }}/{{ item }}.git"
    dest: "{{ vim_dir }}/local/{{ item }}"
  loop:
    - vim-tomorrow-theme
    - vim-custom-snippets
    - restore_view.vim
    - vim-startmode

- name: Package > Vim > install plugins
  become_user: "{{ user_id }}"
  command:
    cmd: vim +PlugInstall +qall
  register: vim_plug_install
  changed_when: vim_plug_install.stdout | regex_search('Resolving\s+deltas')
