---
- name: Vim > Add jonathonf gpg key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 4AB0F789CBA31744CC7DA76A8CF63AD3F06FC659
    keyring: /etc/apt/trusted.gpg.d/vim-jonathonf.gpg

- name: Vim > Add jonathonf apt repository
  apt_repository:
    repo: "deb [arch={{ dpkg_arch }}] https://ppa.launchpadcontent.net/jonathonf/vim/ubuntu {{ ansible_lsb.codename }} main"
    filename: "vim-jonathonf-{{ ansible_lsb.codename }}"
    state: present

- name: Vim > install vim-gtk3
  package:
    name: vim-gtk3
    state: present
    update_cache: yes

- name: Vim > install YouCompleteMe dependencies
  package:
    name: "{{ item }}"
  loop:
    - build-essential
    - cmake
    - python3-dev

- name: Vim > install tagbar dependencies
  package:
    name: universal-ctags

- name: Vim > create folders
  become_user: "{{ user_id }}"
  file:
    path: "{{ vim_dir }}/{{ item }}"
    state: directory
  loop:
    - autoload
    - local
    - temp/undo
    - temp/backup
    - temp/swap
    - temp/view
    - temp/session
    - files/info

- name: Vim > download plugin manager
  become_user: "{{ user_id }}"
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ vim_dir }}/autoload/plug.vim"

- name: Vim > Plugins > clone forks
  become_user: "{{ user_id }}"
  git:
    repo: "{{ git_https_url }}/{{ item }}.git"
    dest: "{{ vim_dir }}/local/{{ item }}"
  loop:
    - vim-tomorrow-theme
    - vim-custom-snippets
    - restore_view.vim
    - vim-startmode

- name: Vim > install plugins
  become_user: "{{ user_id }}"
  command:
    cmd: vim +PlugInstall +qall
  register: vim_plug_install
  changed_when: vim_plug_install.stdout | regex_search('Resolving\s+deltas')
