---
# References:
#   - https://www.virtualbox.org/wiki/Linux_Downloads
- name: Virtualbox > Add apt repository
  import_role:
    name: apt_add_repository
  vars:
    repo_name: virtualbox
    repo_source: "deb https://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib"
    key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Virtualbox > Install
  apt:
    name: virtualbox
    state: present

- name: Virtualbox > Ensure vboxusers group exists
  group:
    name: vboxusers
    state: present

# Necessary to detect usb devices
- name: Virtualbox > Add user to vboxusers group
  user:
    name: "{{ user_id }}"
    groups: vboxusers
    append: true

- name: Virtualbox > Extension Pack > Accept license
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    vtype: select
    value: 'true'

# Add USB 2.0 and USB 3.0 support
- name: Virtualbox > Extension Pack > Install
  apt:
    name: virtualbox-ext-pack
    state: present
