---
# References:
#   - https://www.virtualbox.org/wiki/Linux_Downloads
#   - yum repo: https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
- name: Virtualbox > Add repository (apt)
  import_role:
    name: add_apt_repository
  vars:
    repo_name: virtualbox
    repo_source: "deb https://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib"
    key_url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
  when: ansible_pkg_mgr == "apt"

- name: Virtualbox > Add yum repository (dnf)
  yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://www.virtualbox.org/download/oracle_vbox_2016.asc
  when:
    - ansible_pkg_mgr == "dnf"
    - ansible_distribution_major_version < "39"  # not yet supported, but present in rpmfusion

- name: Virtualbox > Install
  package:
    name: "{{ virtualbox_package }}"
    state: present

- name: Virtualbox > Ensure vboxusers group exists
  group:
    name: vboxusers
    state: present

# Necessary to detect usb devices
- name: Virtualbox > Add user to vboxusers group
  user:
    name: "{{ user_id }}"
    groups: vboxusers
    append: true
