---
# References:
#   - https://www.virtualbox.org/wiki/Linux_Downloads
- name: Virtualbox > Add gpg keys
  apt_key:
    url: "https://www.virtualbox.org/download/{{ item }}.asc"
    keyring: "/etc/apt/trusted.gpg.d/{{ item }}.gpg"
    state: present
  loop:
    - oracle_vbox_2016
    - oracle_vbox

- name: Virtualbox > Add apt repository
  apt_repository:
    repo: "deb [arch={{ dpkg_arch }}] https://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib"
    filename: "virtualbox-{{ ansible_lsb.codename }}"
    state: present
    update_cache: yes

- name: Virtualbox > Install
  apt:
    name: virtualbox
    state: present

- name: Virtualbox > Extension Pack > Accept license
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    vtype: select
    value: 'true'

- name: Virtualbox > Extension Pack > Install
  apt:
    name: virtualbox-ext-pack
    state: present
