---
# References:
#   - https://www.virtualbox.org/wiki/Linux_Downloads
- name: Virtualbox > Add apt keys
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    - "https://www.virtualbox.org/download/oracle_vbox.asc"

- name: Virtualbox > Add apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib"
    filename: "virtualbox-{{ ansible_lsb.codename }}"
    state: present

- name: Virtualbox > Install
  apt:
    name: virtualbox
    state: present
    update_cache: yes
