---
# References:
#   - https://www.wireshark.org/download.html
#   - https://launchpad.net/~wireshark-dev/+archive/ubuntu/stable
#   - https://www.wireshark.org/docs/wsug_html_chunked/ChBuildInstallUnixInstallBins.html
#   - https://gitlab.com/wireshark/wireshark/blob/master/packaging/debian/README.Debian
- name: Wireshark > Add apt repository
  import_role:
    name: add_apt_repository
  vars:
    repo_name: wireshark
    repo_source: "deb https://ppa.launchpadcontent.net/wireshark-dev/stable/ubuntu {{ ansible_lsb.codename }} main" 
    key_id: A2E402B85A4B70CD78D8A3D9D875551314ECA0F0
  when: ansible_pkg_mgr == "apt"

- name: Wireshark > Install
  package:
    name: wireshark
    state: present

- name: Wireshark > Enable non-superusers to capture packets
  when: ansible_pkg_mgr == "apt"
  block:
    # Questions: debconf-show wireshark-common
    - name: Wireshark > Accept dpkg-reconfigure question
      debconf:
        name: wireshark-common  # TODO: check if this 'name' is correct
        question: wireshark-common/install-setuid
        vtype: select
        value: 'true'
      register: wireshark_common_install_setuid

    - name: Wireshark > Reconfigure dpkg for enabling non-superusers to capture packets
      command: dpkg-reconfigure -f noninteractive wireshark-common
      when: wireshark_common_install_setuid.changed

- name: Wireshark > Add user to wireshark group
  user:
    name: "{{ user_id }}"
    groups: wireshark
    append: true
  register: wireshark_add_user_to_group

- name: Wireshark > Manual step
  debug:
    msg: "For the changes to take effect, log out and log in again."
  when: wireshark_common_install_setuid.changed or wireshark_add_user_to_group.changed
